package com.netpood.admin.netpoodapp.database;

import android.content.Context;

import com.netpood.admin.netpoodapp.adapter.CountryItem;

import java.util.ArrayList;

/**
 * Created by jaber Babaki on 7/21/2016.
 */
public class DataFakeCountry {


  public  String[] name={
    "Jamaica",
    "Saint Kitts & Nevis",
    "Trinidad & Tobago",
    "Saint Vincent & the Grenadines",
    "Dominica",
    "Saint Lucia",
    "Sint Maarten",
    "American Samoa",
    "Guam",
    "Northern Mariana Islands",
    "Montserrat",
    "Turks & Caicos Islands",
    "Grenada",
    "Bermuda",
    "Cayman Islands",
    "US Virgin Islands",
    "British Virgin Islands",
    "Antigua & Barbuda",
    "Anguilla",
    "Barbados",
    "Bahamas",
    "Uzbekistan",
    "Kyrgyzstan",
    "Georgia",
    "Azerbaijan",
    "Turkmenistan",
    "Tajikistan",
    "Nepal",
    "Mongolia",
    "Bhutan",
    "Qatar",
    "Bahrain",
    "United Arab Emirates",
    "Palestine",
    "Oman",
    "Yemen",
    "Saudi Arabia",
    "Kuwait",
    "Iraq",
    "Syria",
    "Jordan",
    "Lebanon",
    "Maldives",
    "Taiwan",
    "Bangladesh",
    "Laos",
    "Cambodia",
    "Macau",
    "Hong Kong",
    "North Korea",
    "Marshall Islands",
    "Micronesia",
    "Tokelau",
    "French Polynesia",
    "Tuvalu",
    "New Caledonia",
    "Kiribati",
    "Samoa",
    "Niue",
    "Cook Islands",
    "Wallis & Futuna",
    "Palau",
    "Fiji",
    "Vanuatu",
    "Solomon Islands",
    "Tonga",
    "Papua New Guinea",
    "Nauru",
    "Brunei Darussalam",
    "Norfolk Island",
    "Timor-Leste",
    "Bonaire, Sint Eustatius & Saba",
    "Curaçao",
    "Uruguay",
    "Suriname",
    "Martinique",
    "Paraguay",
    "French Guiana",
    "Ecuador",
    "Guyana",
    "Bolivia",
    "Guadeloupe",
    "Haiti",
    "Saint Pierre & Miquelon",
    "Panama",
    "Costa Rica",
    "Nicaragua",
    "Honduras",
    "El Salvador",
    "Guatemala",
    "Belize",
    "Falkland Islands",
    "Liechtenstein",
    "Slovakia",
    "Czech Republic",
    "Macedonia",
    "Bosnia & Herzegovina",
    "Slovenia",
    "Croatia",
    "Montenegro",
    "Serbia",
    "Ukraine",
    "San Marino",
    "Monaco",
    "Andorra",
    "Belarus",
    "Armenia",
    "Moldova",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Bulgaria",
    "Finland",
    "Cyprus",
    "Malta",
    "Albania",
    "Iceland",
    "Ireland",
    "Luxembourg",
    "Portugal",
    "Gibraltar",
    "Greenland",
    "Faroe Islands",
    "Aruba",
    "Eritrea",
    "Saint Helena",
    "Comoros",
    "Swaziland",
    "Botswana",
    "Lesotho",
    "Malawi",
    "Namibia",
    "Zimbabwe",
    "Réunion",
    "Madagascar",
    "Zambia",
    "Mozambique",
    "Burundi",
    "Uganda",
    "Tanzania",
    "Kenya",
    "Djibouti",
    "Somalia",
    "Ethiopia",
    "Rwanda",
    "Sudan",
    "Seychelles",
    "Saint Helena",
    "Diego Garcia",
    "Guinea-Bissau",
    "Angola",
    "Congo (Dem. Rep.)",
    "Congo (Rep.)",
    "Gabon",
    "Equatorial Guinea",
    "São Tomé & Príncipe",
    "Cape Verde",
    "Cameroon",
    "Central African Rep.",
    "Chad",
    "Nigeria",
    "Ghana",
    "Sierra Leone",
    "Liberia",
    "Mauritius",
    "Benin",
    "Togo",
    "Niger",
    "Burkina Faso",
    "Côte d`Ivoire",
    "Guinea",
    "Mali",
    "Mauritania",
    "Senegal",
    "Gambia",
    "Libya",
    "Tunisia",
    "Algeria",
    "Morocco",
    "South Sudan",
    "Iran",
    "Myanmar",
    "Sri Lanka",
    "Afghanistan",
    "Pakistan",
    "India",
    "Turkey",
    "China",
    "Vietnam",
    "South Korea",
    "Japan",
    "Thailand",
    "Singapore",
    "New Zealand",
    "Philippines",
    "Indonesia",
    "Australia",
    "Malaysia",
    "Venezuela",
    "Colombia",
    "Chile",
    "Brazil",
    "Argentina",
    "Cuba",
    "Mexico",
    "Peru",
    "Germany",
    "Poland",
    "Norway",
    "Sweden",
    "Denmark",
    "United Kingdom",
    "Austria",
    "Y-land",
    "Switzerland",
    "Romania",
    "Italy",
    "Hungary",
    "Spain",
    "France",
    "Belgium",
    "Netherlands",
    "Greece",
    "South Africa",
    "Egypt",
    "Kazakhstan",
    "Russian Federation",
    "Puerto Rico",
    "Dominican Rep.",
    "Canada",
    "USA",
  };

  public  String[] shortName={
    "JM       ",
    "KN    ",
    "TT  ",
    "VC      ",
    "DM        ",
    "LC           ",
    "SX            ",
    "AS              ",
    "GU    ",
    "MPs        ",
    "MS          ",
    "TC       ",
    "GD       ",
    "BM       ",
    "KY              ",
    "VI  ",
    "VG       ",
    "AG  ",
    "AI        ",
    "BB        ",
    "BS       ",
    "UZ          ",
    "KG          ",
    "GE       ",
    "AZ          ",
    "TM            ",
    "TJ          ",
    "NP     ",
    "MN        ",
    "BT      ",
    "QA     ",
    "BH       ",
    "AE     ",
    "PS         ",
    "OM    ",
    "YE     ",
    "SA            ",
    "KW      ",
    "IQ    ",
    "SY     ",
    "JO      ",
    "LB       ",
    "MV        ",
    "TW      ",
    "BD          ",
    "LA    ",
    "KH        ",
    "MO     ",
    "HK         ",
    "KP           ",
    "MH ",
    "FM          ",
    "TK       ",
    "PF ",
    "TV      ",
    "NC             ",
    "KI        ",
    "WS     ",
    "NU    ",
    "CK            ",
    "WF",
    "PW     ",
    "FJ    ",
    "VU       ",
    "SB",
    "TO     ",
    "PG ",
    "NR     ",
    "BN  ",
    "NF              ",
    "TL           ",
    "BQ       ",
    "CW       ",
    "UY       ",
    "SR        ",
    "MQ          ",
    "PY        ",
    "GF             ",
    "EC       ",
    "GY      ",
    "BO       ",
    "GP          ",
    "HT     ",
    "PM        ",
    "PA      ",
    "CR          ",
    "NI         ",
    "HN        ",
    "SV           ",
    "GT         ",
    "BZ      ",
    "FK ",
    "LI             ",
    "SK        ",
    "CZ              ",
    "MK         ",
    "BA     ",
    "SI        ",
    "HR       ",
    "ME          ",
    "RS      ",
    "UA       ",
    "SM          ",
    "MC      ",
    "AD       ",
    "BY       ",
    "AM       ",
    "MD       ",
    "EE       ",
    "LV      ",
    "LT         ",
    "BG        ",
    "FI       ",
    "CY      ",
    "MT     ",
    "AL       ",
    "IS       ",
    "IE       ",
    "LU          ",
    "PT        ",
    "GI         ",
    "GL         ",
    "FO             ",
    "AW     ",
    "ER       ",
    "SH            ",
    "KM       ",
    "SZ         ",
    "BW        ",
    "LS       ",
    "MW      ",
    "NA       ",
    "ZW        ",
    "RE       ",
    "MG          ",
    "ZM      ",
    "MZ          ",
    "BI       ",
    "UG      ",
    "TZ        ",
    "KE     ",
    "DJ        ",
    "SO       ",
    "ET        ",
    "RW      ",
    "SD     ",
    "SC          ",
    "SH          ",
    "IO            ",
    "GW            ",
    "AO             ",
    "CD      ",
    "CG  ",
    "GA            ",
    "GQ     ",
    "ST  ",
    "CV    ",
    "CM          ",
    "CF        ",
    "TD     ",
    "NG    ",
    "GH       ",
    "SL     ",
    "LR            ",
    "MU       ",
    "BJ         ",
    "TG     ",
    "NE    ",
    "BF     ",
    "CI            ",
    "GN             ",
    "ML      ",
    "MR    ",
    "SN          ",
    "GM       ",
    "LY      ",
    "TN     ",
    "DZ       ",
    "MA       ",
    "SS       ",
    "IR           ",
    "MM    ",
    "LK       ",
    "AF         ",
    "PK           ",
    "IN        ",
    "TR     ",
    "CN      ",
    "VN     ",
    "KR       ",
    "JP           ",
    "TH     ",
    "SG        ",
    "NZ         ",
    "PH           ",
    "ID           ",
    "AU         ",
    "MY         ",
    "VE        ",
    "CO         ",
    "CL        ",
    "BR     ",
    "AR      ",
    "CU         ",
    "MX    ",
    "PE      ",
    "DE    ",
    "PL       ",
    "NO      ",
    "SE      ",
    "DK      ",
    "GB       ",
    "AT              ",
    "YL       ",
    "CH      ",
    "RO           ",
    "IT       ",
    "HU     ",
    "ES       ",
    "FR     ",
    "BE      ",
    "NL",
    "GR           ",
    "ZA      ",
    "EG            ",
    "KZ     ",
    "RU          ",
    "PR   ",
    "DO           ",
    "CA              ",
    "US      ",

  };

  public  String[] codeCountry={
    "1876       ",
    "1869    ",
    "1868  ",
    "1784      ",
    "1767        ",
    "1758           ",
    "1721            ",
    "1684              ",
    "1671    ",
    "1670        ",
    "1664          ",
    "1649       ",
    "1473       ",
    "1441       ",
    "1345              ",
    "1340  ",
    "1284       ",
    "1268  ",
    "1264        ",
    "1246        ",
    "1242       ",
    "998          ",
    "996          ",
    "995       ",
    "994          ",
    "993            ",
    "992          ",
    "977     ",
    "976        ",
    "975      ",
    "974     ",
    "973       ",
    "971     ",
    "970         ",
    "968    ",
    "967     ",
    "966            ",
    "965      ",
    "964    ",
    "963     ",
    "962      ",
    "961       ",
    "960        ",
    "886      ",
    "880          ",
    "856    ",
    "855        ",
    "853     ",
    "852         ",
    "850           ",
    "692 ",
    "691          ",
    "690       ",
    "689 ",
    "688      ",
    "687             ",
    "686        ",
    "685     ",
    "683    ",
    "682            ",
    "681",
    "680     ",
    "679    ",
    "678       ",
    "677",
    "676     ",
    "675 ",
    "674     ",
    "673  ",
    "672              ",
    "670           ",
    "599       ",
    "599       ",
    "598       ",
    "597        ",
    "596          ",
    "595        ",
    "594             ",
    "593       ",
    "592      ",
    "591       ",
    "590          ",
    "509     ",
    "508        ",
    "507      ",
    "506          ",
    "505         ",
    "504        ",
    "503           ",
    "502         ",
    "501      ",
    "500 ",
    "423             ",
    "421        ",
    "420              ",
    "389         ",
    "387     ",
    "386        ",
    "385       ",
    "382          ",
    "381      ",
    "380       ",
    "378          ",
    "377      ",
    "376       ",
    "375       ",
    "374       ",
    "373       ",
    "372       ",
    "371      ",
    "370         ",
    "359        ",
    "358       ",
    "357      ",
    "356     ",
    "355       ",
    "354       ",
    "353       ",
    "352          ",
    "351        ",
    "350         ",
    "299         ",
    "298             ",
    "297     ",
    "291       ",
    "290            ",
    "269       ",
    "268         ",
    "267        ",
    "266       ",
    "265      ",
    "264       ",
    "263        ",
    "262       ",
    "261          ",
    "260      ",
    "258          ",
    "257       ",
    "256      ",
    "255        ",
    "254     ",
    "253        ",
    "252       ",
    "251        ",
    "250      ",
    "249     ",
    "248          ",
    "247          ",
    "246            ",
    "245            ",
    "244             ",
    "243      ",
    "242  ",
    "241            ",
    "240     ",
    "239  ",
    "238    ",
    "237          ",
    "236        ",
    "235     ",
    "234    ",
    "233       ",
    "232     ",
    "231            ",
    "230       ",
    "229         ",
    "228     ",
    "227    ",
    "226     ",
    "225            ",
    "224             ",
    "223      ",
    "222    ",
    "221          ",
    "220       ",
    "218      ",
    "216     ",
    "213       ",
    "212       ",
    "211       ",
    "98           ",
    "95    ",
    "94       ",
    "93         ",
    "92           ",
    "91        ",
    "90     ",
    "86      ",
    "84     ",
    "82       ",
    "81           ",
    "66     ",
    "65        ",
    "64         ",
    "63           ",
    "62           ",
    "61         ",
    "60         ",
    "58        ",
    "57         ",
    "56        ",
    "55     ",
    "54      ",
    "53         ",
    "52    ",
    "51      ",
    "49    ",
    "48       ",
    "47      ",
    "46      ",
    "45      ",
    "44       ",
    "43              ",
    "42       ",
    "41      ",
    "40           ",
    "39       ",
    "36     ",
    "34       ",
    "33     ",
    "32      ",
    "31",
    "30           ",
    "27      ",
    "20            ",
    "7     ",
    "7          ",
    "1   ",
    "1           ",
    "1              ",
    "1      ",
  };
  public  ArrayList<CountryItem> getData(Context context) {
    ArrayList<CountryItem> posts = new ArrayList<>();
    for (int i = 0; i <= 230; i++) {
      CountryItem post = new CountryItem();
      post.setCodeCountry(codeCountry[i].trim());
      post.setNameCountry(name[i].trim());
      post.setShortNameCountry(shortName[i].trim());
      posts.add(post);
    }
    return posts;
  }


}
